services:
  plexguard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plexguard
    ports:
      - 4600:4600
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - DATABASE_URL=/app/data/plexguard.db
      - APP_PORT=4600
    volumes:
      - ./data:/app/data
    user: "1000:1000"
    restart: unless-stopped
    networks:
      - plexguard-network

networks:
  plexguard-network:
    driver: bridge
